#!/bin/bash

if [ ! -d "./pulgins/mixins" ]
then
    echo "pulgins/mixins folder DOES NOT exists." && exit 10 
fi



while getopts n:s: flag
do
    case "${flag}" in
        n) name=${OPTARG};;
        s) store=${OPTARG};;
    esac
done

if [ -z "$name" ]
then
    echo "mixins name is required" && exit 5
fi

if [ -z "$store" ]
then
    echo "store name is required" && exit 5
fi


formattedStoreName=$(echo ${store} | sed -r 's/(^|_)([a-z])/\U\2/g')
echo $formattedStoreName

echo "
import Vue from 'vue'

const mixins={
	computed:{
		all${formattedStoreName}Data(){
			return this.\$store.getters["${store}/getAllData"]
			
		},
		all${formattedStoreName}List(){
			return this.\$store.getters["${store}/getAllList"];
		},
		${store}TotalPages(){
			return this.\$store.getters["${store}/getTotalPages"];
		},	

	}
}

Vue.mixin(mixins);

" >> "plugins/mixins/${name}.js"
echo "done!";

